version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
      - run:
          name: Running tests
          command: |
            . .venv/bin/activate
            pytest
      - store_artifacts:
          path: test-reports/
          destination: python_app

    build:
      working_directory: /app
      docker:
        - image: docker:17.05.0-ce-git
      steps:
        - checkout
        - setup_remote_docker
        - restore_cache:
            keys:
              - v1-{{ .Branch }}
            paths:
              - /caches/ocr-p13.tar
        - run:
            name: Load Docker image layer cache
            command: |
              set +o pipefail
              docker load -i /caches/ocr-p13.tar | true
        - run:
            name: Build application Docker image
            command: |
              docker build --cache-from=ocr-p13 -t ${DOCKER_IMG} .
        - run:
            name: Save Docker image layer cache
            command: |
              mkdir -p /caches
              docker save -o /caches/ocr-p13.tar ${DOCKER_IMG}
        - save_cache:
            key: v1-{{ .Branch }}-{{ epoch }}
            paths:
              - /caches/ocr-p13.tar
        - deploy-hub:
            name: Push Docker image to docker hub
            command: |
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push ${DOCKER_IMG}:${CIRCLE_SHA1}
