version: 2.1

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - docker-hub-creds
jobs:
  build:
    docker:
      - image: cimg/python:3.9
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
      - run:
          name: Running tests
          command: |
            . .venv/bin/activate
            pytest

      - setup_remote_docker

      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=ocr-p13 -t $DOCKER_IMG .
