version: 2.1

commands:
  install-deps:
    steps:
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r requirements.txt
  save-cache:
    steps:
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
  docker-bp:
    steps:
      - run:
          name: Build application Docker image
          command: |
            docker build -t $DOCKER_IMG .
      - run:
          name: Push Docker image to docker hub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASS
            docker tag $DOCKER_IMG $DOCKER_IMG:$CIRCLE_SHA1
            docker push $DOCKER_IMG:$CIRCLE_SHA1
jobs:
  Run-Tests:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - install-deps
      - run:
          name: Running Tests
          command: |
            . .venv/bin/activate
            pytest
      - save-cache

  Run-Lintings:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - install-deps
      - run:
          name: Running Linting
          command: |
            . .venv/bin/activate
            flake
      - save-cache

  Docker-Image:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t $DOCKER_IMG .
      - run:
          name: Push Docker image to docker hub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASS
            docker tag $DOCKER_IMG $DOCKER_IMG:$CIRCLE_SHA1
            docker push $DOCKER_IMG:$CIRCLE_SHA1

workflows:
  Run-Checkups:
    jobs:
      - Run-Tests
      - Run-Lintings

  Docker-Hub-Push:
    jobs:
      - Docker-Image:
          requires:
            - "Run-Checkups"
          filters:
            branches:
              only: master
